name: "Sweet Home 3D for YHDT card"
description: "Sweet Home 3D for Your Home Digital Twin Card (aka floor3d-card)"
slug: "sh3d-ha"
version: "0.0.26"
codenotary: adizanni@gmail.com
#ingress: true
#ingress_port: 8080
#ingress_entry: "sweethome3djsha/"
host_network: true
webui: http://[HOST]:[PORT:8080]/sweethome3djsha
map:
  - share:rw
  - homeassistant_config:rw
arch:
  - amd64
  - aarch64
options:
  model_folder: homes
  export_to_HA_folder: homes
  resources_folder: user
schema:
  model_folder: str
  export_to_HA_folder: str
  resources_folder: str
image: adizanni/sh3d-ha-addon-{arch}
