name: "Sweet Home 3D for YHDT card"
description: "Sweet Home 3D for Your Home Digital Twin Card (aka floor3d-card)"
version: "1.0.30"
codenotary: adizanni@gmail.com
#ingress: true
#ingress_port: 8080
#ingress_entry: "/sweethome3djsha/"
#ingress_stream: true
host_network: true
webui: http://homeassistant.local:[PORT:8080]/sweethome3djsha
slug: "sh3d-ha"
map:
  - share:rw
  - homeassistant_config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  model_folder: homes
  export_to_HA_folder: homes
schema:
  model_folder: str
  export_to_HA_folder: str
